Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

revenue_by_country = df.groupby('Country')['Revenue'].sum().sort_values(ascending=False)
# Plotting
fig, ax = plt.subplots(figsize=(12, 6))
revenue_by_country.plot(kind='bar', ax=ax, color='skyblue')

# Menambahkan label dan judul
ax.set_xlabel('Negara')
ax.set_ylabel('Total Pendapatan')
ax.set_title('Total Pendapatan per Negara')

plt.xticks(rotation=45, ha='right')  # Memutar label sumbu x untuk memperbaiki tampilan
plt.tight_layout()  # Menyusun layout agar lebih rapi
plt.show()

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn[6], line 3[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m----> 3[0m revenue_by_country [38;5;241m=[39m [43mdf[49m[38;5;241;43m.[39;49m[43mgroupby[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mCountry[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mRevenue[39;49m[38;5;124;43m'[39;49m[43m][49m[38;5;241m.[39msum()[38;5;241m.[39msort_values(ascending[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m      4[0m [38;5;66;03m# Plotting[39;00m
[0;32m      5[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize[38;5;241m=[39m([38;5;241m12[39m, [38;5;241m6[39m))

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\groupby\generic.py:1416[0m, in [0;36mDataFrameGroupBy.__getitem__[1;34m(self, key)[0m
[0;32m   1407[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, [38;5;28mtuple[39m) [38;5;129;01mand[39;00m [38;5;28mlen[39m(key) [38;5;241m>[39m [38;5;241m1[39m:
[0;32m   1408[0m     [38;5;66;03m# if len == 1, then it becomes a SeriesGroupBy and this is actually[39;00m
[0;32m   1409[0m     [38;5;66;03m# valid syntax, so don't raise warning[39;00m
[0;32m   1410[0m     warnings[38;5;241m.[39mwarn(
[0;32m   1411[0m         [38;5;124m"[39m[38;5;124mIndexing with multiple keys (implicitly converted to a tuple [39m[38;5;124m"[39m
[0;32m   1412[0m         [38;5;124m"[39m[38;5;124mof keys) will be deprecated, use a list instead.[39m[38;5;124m"[39m,
[0;32m   1413[0m         [38;5;167;01mFutureWarning[39;00m,
[0;32m   1414[0m         stacklevel[38;5;241m=[39mfind_stack_level(),
[0;32m   1415[0m     )
[1;32m-> 1416[0m [38;5;28;01mreturn[39;00m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__getitem__[39;49m[43m([49m[43mkey[49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\base.py:248[0m, in [0;36mSelectionMixin.__getitem__[1;34m(self, key)[0m
[0;32m    246[0m [38;5;28;01melse[39;00m:
[0;32m    247[0m     [38;5;28;01mif[39;00m key [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mobj:
[1;32m--> 248[0m         [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mColumn not found: [39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m"[39m)
[0;32m    249[0m     subset [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mobj[key]
[0;32m    250[0m     ndim [38;5;241m=[39m subset[38;5;241m.[39mndim

[1;31mKeyError[0m: 'Column not found: Revenue'
KeyError: 'Column not found: Revenue'

